#******************************************************************************#
#                                                                              #
#               Makefile for YOUR_PROJECT_NAME                                 #
#               Created on : Mon Oct  5 17:49:44 2015                          #
#               Made by : David "Thor" GIRON <thor@staff.42.fr>                #
#                                                                              #
#******************************************************************************#

# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = YOUR_PROJECT_NAME.fr.pdf YOUR_PROJECT_NAME.en.pdf YOUR_PROJECT_NAME.ro.pdf


# List the files included in the document, or leave empty
DEPS = 


# Relative path to the LaTeX documentclass setup files
RELPATH = ../resources/latex


# You should not touch this
include $(RELPATH)/Makefile.LaTeX



#******************************************************************************#
