#******************************************************************************#
#                                                                              #
#               Makefile for FT_DATA                                           #
#               Created on : Mon Oct  5 17:49:44 2015                          #
#               Made by : David "Thor" GIRON <thor@staff.42.fr>                #
#                                                                              #
#******************************************************************************#

# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = FT_DATA.en.pdf #FT_DATA.fr.pdf FT_DATA.en.pdf FT_DATA.ro.pdf


# List the files included in the document, or leave empty
DEPS = 


# Relative path to the LaTeX documentclass setup files
RELPATH = ../resources/latex


# You should not touch this
include $(RELPATH)/Makefile.LaTeX



#******************************************************************************#
